import type { Metadata } from 'next';
import { andersonGrotesk } from '../font';
import '../globals.css';
import Header from '../components/header';

import { Providers } from '../Providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<Header />

			<Providers>{children}</Providers>
		</>
	);
}
