import type { Metadata } from 'next';
import { andersonGrotesk } from '../font';
import '../globals.css';
import Header from '../components/Header';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className=" scroll-smooth">
			<body
				className={`${andersonGrotesk.variable} scroll-smooth bg-primary-green font-andersonGrotesk`}
			>
				<Header />

				{children}
			</body>
		</html>
	);
}
