import type { Metadata } from 'next';
import { andersonGrotesk } from './font';
import './globals.css';
import { Providers } from './Providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className=" scroll-smooth">
			<body
				className={`${andersonGrotesk.variable} font-teleGrotesk relative `}
				// className={`${andersonGrotesk.variable} font-teleGrotesk relative flex flex-row flex-nowrap `}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
