import type { Metadata } from 'next';
import { andersonGrotesk } from '../font';
import '../globals.css';
import SideMenu from '@/app/components/side-menu';
import { getServerAuthSession } from '@/server/auth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default async function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	const status = await getServerAuthSession();
	// console.log(status);
	if (!status) {
		// User unauthenticated, redirect to home
		redirect('/sign-in');
	}
	return (
		<main className=" overflow-none relative box-border flex h-screen w-full flex-row flex-nowrap items-start justify-start bg-[#fff]">
			<SideMenu />
			<div className="box-border flex h-full w-full flex-col items-start justify-start overflow-auto bg-[#fff] px-4 py-20 text-black md:px-8 lg:pr-12">
				{children}
			</div>
		</main>
	);
}
